version: '2'
networks:
  consul:
services:
  consul1:
    image: consul:1.13.3
    container_name: node1
    volumes: 
      - /data/consul/conf_with_acl:/consul/config
    command: agent -server -ui -bootstrap-expect=2 -node=node1 -bind=0.0.0.0 -client=0.0.0.0 -config-dir=/consul/config
    ports:
      - 8500:8500
    networks:
      - consul
  consul2:
    image: consul:1.13.3
    container_name: node2
    volumes:
      - /data/consul/conf_with_acl:/consul/config
    command: agent -server -retry-join=node1 -node=node2 -bind=0.0.0.0 -client=0.0.0.0 -config-dir=/consul/config
    depends_on:
      - consul1
    networks:
      - consul
  consul3:
    image: consul:1.13.3
    volumes:
      - /data/consul/conf_with_acl:/consul/config
    container_name: node3
    command: agent -server -retry-join=node1 -node=node3 -bind=0.0.0.0 -client=0.0.0.0 -config-dir=/consul/config
    depends_on:
      - consul1
    networks:
      - consul
